BRITISH_CAMPAIGN = [
    # mission 1
    ['Defense of Mons:', 
     'The British Expeditionary Force, a highly trained but',
     'relatively small professional army, faced the numerically',
     'superior German First Army near Mons, Belgium.  The ',
     'British soldiers, armed with their rapid and precise rifle',
     'fire, caused heavy casualties and temporarily slowed the',
     'German advance. This effectiveness earned the respect of ',
     'the Germans, who reportedly believed they were facing ',
     'machine guns instead of rifles.',
     '',
     'Despite their tactical success, the British were eventually',
     'forced to retreat as the Germans brought in reinforcements',
     'and threatened to outflank the BEF. This retreat marked the',
     'beginning of the long and grueling Western Front campaign.'
     ],
    # mission 2
    ['First Battle of Ypres', 
     'The British Expeditionary Force (BEF), alongside French and',
     'Belgian troops, faced relentless German assaults near Ypres,',
     'a key strategic position. The British aimed to prevent the',
     'Germans from breaking through to the coast, which would\'ve',
     'jeopardized Allied supply lines and Britain\'s ability to ',
     'reinforce its troops.',
     '',
     'Fighting was intense, both sides suffering heavy casualties.',
     'British troops, despite being outnumbered and under immense',
     'pressure, displayed remarkable resilience and determination.',
     'Their defense at Ypres earned them a reputation for bravery',
     'and endurance, though it came at a high cost, including the',
     'loss of many experienced soldiers from prior conflicts.'
     ],
    # mission 3
    ['Somme Offensive', 
     'The offensive marked the debut of many British volunteer',
     'soldiers, part of Lord Kitchener\'s "New Army," fighting',
     'alongside seasoned troops. Despite extensive planning, the ',
     'first day of the offensive proved catastrophic—Britain',
     'suffered nearly 60,000 casualties, making it the bloodiest',
     'single day in its military history.',
     '',
     'Ultimately, the Somme Offensive underscored the brutal',
     'nature of trench warfare, with massive casualties on both',
     'sides and only minor territorial changes. Yet, it did contribute' ,
     'to wearing down the German army, beginning a long war of',
     'attrition that would continue on the Western Front.',
     ''
     ],
    # mission 4
    ['Cambrai - Tank Revolution', 
     'From the British perspective, Cambrai was an opportunity to',
     'break through the stalemated trench lines. The battle began ',
     'with a surprise attack led by the British Third Army, ',
     'supported by hundreds of tanks, artillery, and infantry. The ',
     'tanks successfully crushed barbed wire defenses and helped ',
     'the British achieve significant territorial gains on the ',
     'first day, a rare feat in trench warfare.',
     '',
     'Cambrai was a tactical and technological milestone. It ',
     'demonstrated the potential of armored warfare and marked ',
     'a shift towards more dynamic and innovative military ',
     'strategies.  For the British, it was a step forward in ',
     'adapting to the challenges of modern war.'
     ],
    # mission 5
    ['Hundred Days Offensive', 
     'The British, along with Australian, Canadian, and other',
     'Allied forces, utilized combined arms tactics, including',
     'infantry, tanks, artillery, and aircraft, to achieve',
     'breakthroughs that had eluded them earlier in the war.',
     '',
     'British forces continued to push the Germans back, liberating',
     'occupied territories and disrupting their supply lines.',
     'The Hundred Days Offensive demonstrated the evolution',
     'of British military tactics and strategy, moving away from',
     'static trench warfare to more dynamic and coordinated',
     'operations. It also reflected the immense sacrifice and',
     'determination of British soldiers in overcoming years of ',
     'grueling stalemate to contribute to the eventual armistice.'
     ],
]

FRENCH_CAMPAIGN = [
    # mission 1
    ['Battle of the Frontiers', 
     'The initial fighting in Alsace-Lorraine during World War I',
     'occurred in August 1914, as part of France\'s bold Plan XVII.',
     'From the French perspective, this offensive was not only a',
     'military maneuver but also an emotional and symbolic ',
     'attempt to reclaim territory lost to Germany in 1871.',
     '',
     'These early engagements highlighted the harsh realities of ',
     'modern warfare. French troops faced entrenched German ',
     'defenses and heavy casualties. By mid-August, the French ',
     'had been pushed back to their starting positions, marking a ',
     'sobering beginning to the long and grueling war ahead.',
     '',
     ''
     ],
    # mission 2
    ['First Battle of the Marne', 
     'The French army mounted a decisive counteroffensive against',
     'the German forces, who were executing the Schlieffen Plan',
     'to quickly capture Paris. The French mobilized all possible',
     'resources, including famously using Parisian taxis to transport ',
     'troops to the front lines, symbolizing the urgency and',
     'determination of the effort. This became known as the "Taxi  ',
     'de la Marne" and is celebrated as a moment of national unity ',
     'and ingenuity.',
     '',
     'The French public viewed this battle as a heroic stand that ',
     'saved Paris and demonstrated their resilience and courage in ',
     'the face of invasion.',
     ''
     ],
    # mission 3
    ['Verdun - "They Shall Not Pass', 
     'The Germans aimed to "bleed France white" by attacking ',
     'Verdun, a city with deep historical and cultural ',
     'significance to the French. General Philippe Pétain led ',
     'the French forces, rallying them with the motto "Ils ne ',
     'passeront pas!" ("They shall not pass!"), which became a ',
     'powerful symbol of Frnech defiance.',
     '',
     'Despite the horrific conditions, the French considered',
     'their eventual ability to hold Verdun and later push the ',
     'Germans back as a matter of national pride. It became a ',
     'symbol of their unwavering resolve and courage.',
     '',
     ''
     ],
    # mission 4
    ['Nivelle Offensive', 
     'Led by General Robert Nivelle, the French forces attempted',
     'to break through German lines along the Aisne River and',
     'achieve a rapid victory. Nivelle\'s promise of a swift and ',
     'decisive triumph boosted morale initially, but the offensive',
     'quickly turned into a disaster. The Germans were well-',
     'prepared, and the French suffered massive casualties in the ',
     'face of strong resistance.',
     '',
     'The failed offensive led to widespread disillusionment among ',
     'troops and the population. It triggered mutinies within the',
     'French army, as soldiers protested against the perceived ',
     'futility of the war and the leadership\'s disregard for ',
     'their lives.'
     ],
    # mission 5
    ['Hundred Days Offensive', 
     'the Hundred Days Offensive symbolized the culmination of ',
     'their endurance and sacrifices throughout the war. Under the',
     'leadership of Marshal Ferdinand Foch, the French forces played',
     'a central role in the Allied strategy, contributing decisively ',
     'to key battles, such as the Second Battle of the Marne and the',
     'Battle of Saint-Mihiel. The French fought valiantly to liberate',
     'their occupied territories, reclaiming towns and villages from ',
     'German control.',
     '',
     'The offensive demonstrated the strength of the French army,',
     'which had recovered from earlier setbacks and proved its ',
     'resilience.  The successes of the French and their Allies during',
     'these final months ultimately led to the Armistice'
     ],
]

GERMAN_CAMPAIGN = [
    # mission 1
    ['Schlieffen Plan', 
     'The plan, devised by General Count Alfred von Schlieffen ',
     'years before World War I, aimed to quickly defeat France ',
     'by advancing through Belgium and Luxembourg, then pivoting ',
     'to confront russia on the Eastern Front. It was designed to ',
     'avoid a prolonged two-front war.',
     '',
     'Initially, the Germans viewed the plan as a bold and efficient ',
     'strategy.  The early stages of the invasion were successful, ',
     'with rapid advances into Belgium and northern France. ',
     'However, from the German perspective, several challenges ',
     'arose during execution that ultimately undermined the plan.',
     '',
     ''
     ],
    # mission 2
    ['First Battle of Ypres', 
     'The Germans aimed to break through the Allied lines and',
     'secure key positions in Belgium, including the vital town of',
     'Ypres.  The battle was part of their efforts to gain control ',
     'over the Channel ports and outflank the Allies.  For German ',
     'forces, the battle represented a chance to secure a decisive',
     'advantage before the onset of winter.',
     '',
     'Despite initial successes, the Germans faced fierce resistance',
     'from the Allies, including British, French, and Belgian forces,',
     'who were determined to hold their ground. German troops,',
     'including a large number of inexperienced recruits known as ',
     'the "Kindermord" (or "Massacre of the Innocents"), suffered ',
     'heavy casualties in the relentless fighting.'
     ],
    # mission 3
    ['Verdun Offensive', 
     'The Germans meticulously prepared for the assault, amassing',
     'troops and artillery to create an overwhelming bombardment.',
     'Initially, the offensive achieved some success, as German',
     'forces made gains and pushed towards Verdun. However, the ',
     'French defense, led by General Philippe Pétain, proved ',
     'tenacious and unyielding.',
     '',
     'Verdun became a grueling and costly stalemate. The relentless',
     'French counterattacks and the resilience of the defenders ',
     'forced the Germans into a prolonged battle that drained their ',
     'resources and morale. By the end of the attack, Germany had',
     'failed to achieve its objective of swiftly defeating France,',
     'and the losses on both sides heavily affected morale.'
     ],
    # mission 4
    ['Spring Offensives', 
     'The Spring Offensives of 1918, AKA the "Kaiserschlacht"',
     'or "Kaiser\'s Battle," represented Germany\'s last major ',
     'attempt to secure victory in World War I before the full ',
     'force of American troops could bolster the Allies. From ',
     'the German perspective, these offensives were seen as a ',
     'bold but desperate gamble to break the stalemate on the ',
     'Western Front.',
     '',
     'The rapid advances stretched German supply lines, and their ',
     'troops, already suffering from food shortages and exhaustion,',
     'could not sustain the momentum. Meanwhile, the Allies, ',
     'supported by fresh American forces, regrouped and ',
     'counterattacked effectively.'
     ],
    # mission 5
    ['Hundred Days Defence', 
     'The defence was characterized by coordinated Allied attacks,',
     'spearheaded by the French, British, and newly arrived ',
     'American forces, employing combined arms tactics. The ',
     'Germans viewed the relentless series of offensives as ',
     'overwhelming, as their previously robust defenses were ',
     'systematically broken. Their army, already weakened by years ',
     'of attritional warfare, food shortages, and internal unrest, ',
     'struggled to mount effective resistance.',
     '',
     'The loss of key positions, such as the Hindenburg Line, ',
     'shattered hopes of maintaining a defensive stalemate.',
     'The constant pressure also exacerbated political instability ',
     'at home, ending in calls for the abdication of the Kaiser.'
     ],
]
