BRITISH_CAMPAIGN = [
    # mission 1
    ['Defense of Mons:', 
     'The British Expeditionary Force, a highly trained but',
     'relatively small professional army, faced the numerically',
     'superior German First Army near Mons, Belgium.  The ',
     'British soldiers, armed with their rapid and precise rifle',
     'fire, caused heavy casualties and temporarily slowed the',
     'German advance. This effectiveness earned the respect of ',
     'the Germans, who reportedly believed they were facing ',
     'machine guns instead of rifles.',
     '',
     'Despite their tactical success, the British were eventually',
     'forced to retreat as the Germans brought in reinforcements',
     'and threatened to outflank the BEF. This retreat marked the',
     'beginning of the long and grueling Western Front campaign.'
     ],
    # mission 2
    ['First Battle of Ypres', 
     'The British Expeditionary Force (BEF), alongside French and',
     'Belgian troops, faced relentless German assaults near Ypres,',
     'a key strategic position. The British aimed to prevent the',
     'Germans from breaking through to the coast, which would\'ve',
     'jeopardized Allied supply lines and Britain\'s ability to ',
     'reinforce its troops.',
     '',
     'Fighting was intense, both sides suffering heavy casualties.',
     'British troops, despite being outnumbered and under immense',
     'pressure, displayed remarkable resilience and determination.',
     'Their defense at Ypres earned them a reputation for bravery',
     'and endurance, though it came at a high cost, including the',
     'loss of many experienced soldiers from prior conflicts.'
     ],
    # mission 3
    ['Somme Offensive', 
     'The offensive marked the debut of many British volunteer',
     'soldiers, part of Lord Kitchener\'s "New Army," fighting',
     'alongside seasoned troops. Despite extensive planning, the ',
     'first day of the offensive proved catastrophic—Britain',
     'suffered nearly 60,000 casualties, making it the bloodiest',
     'single day in its military history.',
     '',
     'Ultimately, the Somme Offensive underscored the brutal',
     'nature of trench warfare, with massive casualties on both',
     'sides and only minor territorial changes. Yet, it did contribute' ,
     'to wearing down the German army, beginning a long war of',
     'attrition that would continue on the Western Front.',
     ''
     ],
    # mission 4
    ['Cambrai - Tank Revolution', 
     'From the British perspective, Cambrai was an opportunity to',
     'break through the stalemated trench lines. The battle began ',
     'with a surprise attack led by the British Third Army, ',
     'supported by hundreds of tanks, artillery, and infantry. The ',
     'tanks successfully crushed barbed wire defenses and helped ',
     'the British achieve significant territorial gains on the ',
     'first day, a rare feat in trench warfare.',
     '',
     'Cambrai was a tactical and technological milestone. It ',
     'demonstrated the potential of armored warfare and marked ',
     'a shift towards more dynamic and innovative military ',
     'strategies.  For the British, it was a step forward in ',
     'adapting to the challenges of modern war.'
     ],
    # mission 5
    ['Hundred Days Offensive', 
     'The British, along with Australian, Canadian, and other',
     'Allied forces, utilized combined arms tactics, including',
     'infantry, tanks, artillery, and aircraft, to achieve',
     'breakthroughs that had eluded them earlier in the war.',
     '',
     'British forces continued to push the Germans back, liberating',
     'occupied territories and disrupting their supply lines.',
     'The Hundred Days Offensive demonstrated the evolution',
     'of British military tactics and strategy, moving away from',
     'static trench warfare to more dynamic and coordinated',
     'operations. It also reflected the immense sacrifice and',
     'determination of British soldiers in overcoming years of ',
     'grueling stalemate to contribute to the eventual armistice.'
     ],
]

FRENCH_CAMPAIGN = [
    # mission 1
    ['Battle of the Frontiers', 
     'The initial fighting in Alsace-Lorraine during World War I',
     'occurred in August 1914, as part of France\'s bold Plan XVII.',
     'From the French perspective, this offensive was not only a',
     'military maneuver but also an emotional and symbolic ',
     'attempt to reclaim territory lost to Germany in 1871.',
     '',
     'These early engagements highlighted the harsh realities of ',
     'modern warfare. French troops faced entrenched German ',
     'defenses and heavy casualties. By mid-August, the French ',
     'had been pushed back to their starting positions, marking a ',
     'sobering beginning to the long and grueling war ahead.',
     '',
     ''
     ],
    # mission 2
    ['First Battle of the Marne', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 3
    ['Verdun - "They Shall Not Pass', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 4
    ['Nivelle Offensive', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 5
    ['Hundred Days Offensive', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
]

GERMAN_CAMPAIGN = [
    # mission 1
    ['Schlieffen Plan', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 2
    ['First Battle of Ypres', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 3
    ['Verdun Offensive', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 4
    ['Spring Offensives', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
    # mission 5
    ['Hundred Days Defence', 
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     '',
     ''
     ],
]
